import { useEffect, useRef } from 'react';
import { portfolioData } from '../../data/portfolio';
import { Code2, Network, ArrowUpRight } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
// @ts-ignore
import profile2 from '../../assets/images/profile-2.jpg';
// @ts-ignore
import profile3 from '../../assets/images/profile-3.jpg';
// @ts-ignore
import profile5 from '../../assets/images/profile-5.jpg';
gsap.registerPlugin(ScrollTrigger);
export function About(){const ref=useRef<HTMLElement>(null);useEffect(()=>{const ctx=gsap.context(()=>{gsap.fromTo('.about-item',{opacity:0,y:30},{opacity:1,y:0,duration:.8,stagger:.1,ease:'power3.out',scrollTrigger:{trigger:ref.current,start:'top 75%'}});},ref);return()=>ctx.revert();},[]);return <section ref={ref} id="about" className="py-32 md:py-44"><div className="page-shell"><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-16 lg:gap-24"><div className="about-item"><p className="section-label mb-5">01 // About</p><h2 className="section-title">Curious by<br/><span className="text-[var(--iris)]">default.</span></h2><p className="body-copy mt-8 max-w-md">I enjoy turning complex ideas into useful software. My work sits between artificial intelligence, machine learning and thoughtful product design.</p><a href="#contact" className="inline-flex items-center gap-2 mt-8 ghost-link">Get in touch <ArrowUpRight size={14}/></a></div><div className="about-item"><div className="grid grid-cols-2 gap-3 h-[440px] md:h-[560px]"><div className="h-[78%] self-end overflow-hidden rounded-[10px]"><img src={profile5} alt="Abhijit" className="w-full h-full object-cover grayscale hover:grayscale-0 transition-all duration-700"/></div><div className="h-full overflow-hidden rounded-[10px]"><img src={profile2} alt="Abhijit portrait" className="w-full h-full object-cover"/></div></div></div></div><div className="grid md:grid-cols-2 gap-6 mt-24"><div className="about-item graphite-card"><div className="flex items-center gap-3 mb-6"><Code2 size={18} className="text-[var(--iris)]"/><h3 className="text-lg tracking-[.04em]">Software</h3></div><div className="flex flex-wrap gap-x-6 gap-y-4">{portfolioData.skills.programming.map(s=><span key={s} className="text-sm text-[var(--ash)] hover:text-white transition-colors">{s}</span>)}</div></div><div className="about-item graphite-card"><div className="flex items-center gap-3 mb-6"><Network size={18} className="text-white"/><h3 className="text-lg tracking-[.04em]">AI / ML</h3></div><div className="flex flex-wrap gap-x-6 gap-y-4">{portfolioData.skills.ai.map(s=><span key={s} className="text-sm text-[var(--ash)] hover:text-white transition-colors">{s}</span>)}</div></div></div></div></section>}
