import { useEffect, useRef, useState, type ReactNode } from 'react';
import { portfolioData } from './data/portfolio';
import './portfolio-polish.css';
// @ts-ignore local image asset
import profile1 from './assets/images/profile-1.jpg';
// @ts-ignore local image asset
import profile2 from './assets/images/profile-2.jpg';
// @ts-ignore local image asset
import profile3 from './assets/images/profile-3.jpg';

function Arrow({ diagonal = true }: { diagonal?: boolean }) { return <span aria-hidden="true" className={`arrow-icon ${diagonal ? 'diagonal' : ''}`}>↗</span>; }
function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) { const ref=useRef<HTMLDivElement>(null); useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){node.classList.add('is-visible');observer.disconnect();}},{threshold:.12});observer.observe(node);return()=>observer.disconnect();},[]);return <div ref={ref} className={`reveal ${className}`}>{children}</div>; }

function App() {
 const [menuOpen,setMenuOpen]=useState(false); const [active,setActive]=useState('home');
 useEffect(()=>{const sections=['home','about','work','credentials','contact'];const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id);},{threshold:[.2,.45,.7]});sections.forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el);});return()=>observer.disconnect();},[]);
 const scrollTo=(id:string)=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'});};
 return <div className="site"><div className="grain"/><header className="topbar"><button className="brand" onClick={()=>scrollTo('home')} aria-label="Go home"><span className="brand-mark">AP</span><span>Abhijit Pandey</span></button><nav className={`nav ${menuOpen?'open':''}`}>{['home','about','work','credentials','contact'].map(id=><button key={id} className={active===id?'active':''} onClick={()=>scrollTo(id)}>{id==='work'?'Work':id.charAt(0).toUpperCase()+id.slice(1)}</button>)}</nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><span>{menuOpen?'Close':'Menu'}</span><i>{menuOpen?'×':'↘'}</i></button></header>
 <main>
  <section id="home" className="hero-section"><div className="hero-card"><div className="hero-card-top"><span className="micro">© 2026 / ABHIJIT PANDEY</span><span className="micro desktop-only">B.TECH CSE · AI / ML</span><span className="micro">India</span></div><div className="hero-copy-left"><span className="micro">01 — INTRO</span><p>Developer &amp;<br/>AI/ML student</p></div><div className="hero-copy-right"><span className="tiny-arrow">↘</span><p>Building intelligent<br/>digital experiences</p></div><div className="hero-image-wrap"><img src={profile1} alt="Abhijit Pandey" className="hero-image"/></div><div className="location-pill"><span className="location-dot"/>Located in<br/>India <span className="globe">◎</span></div><div className="hero-name" aria-label={portfolioData.personal.name}><span>Abhijit</span> <span>Pandey</span></div><div className="hero-bottom-note"><span>Scroll to explore</span><span className="scroll-line"/></div></div></section>
  <section id="about" className="editorial-section light-section"><Reveal className="section-intro"><div><span className="micro dark">02 — ABOUT</span><h2>Curious<br/><em>by default.</em></h2></div><p className="lead-copy">{portfolioData.personal.bio}</p></Reveal><div className="about-grid"><Reveal className="about-photo large"><img src={profile2} alt="Abhijit"/></Reveal><Reveal className="about-photo small"><img src={profile3} alt="Abhijit"/></Reveal><Reveal className="about-facts"><span className="micro dark">WHAT I DO</span><p>Turn ideas into useful software — from machine-learning experiments and data workflows to polished web products.</p><div className="fact-list"><span>01 / Artificial Intelligence</span><span>02 / Machine Learning</span><span>03 / Full-stack Development</span><span>04 / Product &amp; UI</span></div></Reveal></div></section>
  <section id="work" className="work-section dark-section"><Reveal className="work-heading"><span className="micro">03 — SELECTED WORK</span><h2>Things<br/><em>I build.</em></h2><p>Selected experiments, products and technical work.</p></Reveal><div className="project-list">{portfolioData.projects.map((project,index)=><Reveal key={project.id} className="project-row"><span className="project-number">0{index+1}</span><div className="project-main"><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.technologies.map(tag=><span key={tag}>{tag}</span>)}</div></div><div className="project-thumb"><img src={project.image} alt=""/></div><a className="project-link" href={project.githubUrl} target="_blank" rel="noreferrer" aria-label={`Open ${project.title}`}><Arrow/></a></Reveal>)}</div></section>
  <section id="credentials" className="credential-section light-section"><Reveal className="credential-head"><div><span className="micro dark">04 — CREDENTIALS</span><h2>Proof of<br/><em>practice.</em></h2></div><a href={portfolioData.personal.linkedin} target="_blank" rel="noreferrer" className="circle-link">LinkedIn <Arrow/></a></Reveal><div className="credential-list">{portfolioData.certifications.map((cert,index)=><a href={cert.url} target="_blank" rel="noreferrer" key={`${cert.name}-${index}`} className="credential-row"><span>0{index+1}</span><div className="credential-logo"><img src={cert.image} alt=""/></div><div><h3>{cert.name}</h3><p>{cert.organization}</p></div><Arrow/></a>)}</div></section>
  <section className="skills-section dark-section"><Reveal><span className="micro">05 — TOOLKIT</span><h2>Made with<br/><em>these.</em></h2></Reveal><div className="skills-grid">{Object.entries(portfolioData.skills).map(([group,skills])=><Reveal key={group} className="skill-group"><span className="micro">{group.toUpperCase()}</span><div>{skills.map(skill=><span key={skill}>{skill}</span>)}</div></Reveal>)}</div></section>
  <section id="contact" className="contact-section"><Reveal className="contact-card"><div className="contact-top"><span className="micro">06 — CONTACT</span><span className="status"><i/> Open to opportunities</span></div><h2>Let's make<br/><em>something.</em></h2><p>Open to internships, collaborations and interesting technical problems.</p><div className="contact-actions"><a href={`mailto:${portfolioData.personal.email}`} className="big-button">Email me <Arrow/></a><a href={`https://github.com/${portfolioData.personal.github}`} className="text-link" target="_blank" rel="noreferrer">GitHub <Arrow/></a><a href={portfolioData.personal.linkedin} className="text-link" target="_blank" rel="noreferrer">LinkedIn <Arrow/></a></div><div className="contact-footer"><span>© 2026 Abhijit Pandey</span><span>Built with curiosity</span></div></Reveal></section>
 </main></div>;
}
export default App;
